"""Pinned, stratified general prompts for the conditional mixture comparison."""
import collections
import hashlib
import json
import random
import urllib.request
from pathlib import Path
from benchmark import read_rows,chat_token_ids
from prepare_data import normalize
ROOT=Path(__file__).resolve().parents[1]
REV='bdd27f4d94b9c1f951818a7da7fd7aeea5dbff1a'

def main():
    from transformers import AutoTokenizer
    cache=ROOT.parents[1]/'work/rust-data-cache'
    source=cache/'dolly-15k.jsonl'
    url=f'https://huggingface.co/datasets/databricks/databricks-dolly-15k/resolve/{REV}'
    if not source.exists():urllib.request.urlretrieve(url+'/databricks-dolly-15k.jsonl',source)
    out=ROOT/'phase2/data/general';out.mkdir(parents=True,exist_ok=True)
    if (out/'train.jsonl').exists():raise SystemExit('General prompts already frozen')
    urllib.request.urlretrieve(url+'/README.md',out/'SOURCE_README.md')
    tokenizer=AutoTokenizer.from_pretrained(ROOT.parents[1]/'work/rust-tokenizer',local_files_only=True)
    forbidden={normalize(x['prompt']) for x in read_rows(ROOT/'phase2/data/evaluation.jsonl')}
    groups=collections.defaultdict(list);seen=set()
    for r in read_rows(source):
        prompt=r['instruction'].strip()+ ('\n\nContext:\n'+r['context'].strip() if r['context'].strip() else '')
        key=normalize(prompt)
        if key in seen or key in forbidden or len(chat_token_ids(tokenizer,prompt))>1024:continue
        seen.add(key)
        groups[r['category']].append({'id':'dolly-'+hashlib.sha256(key.encode()).hexdigest()[:20],'prompt':prompt,'task':r['category'],'source':'databricks/databricks-dolly-15k','revision':REV})
    rows=[];rng=random.Random(20260918)
    for category in sorted(groups):
        rng.shuffle(groups[category]);assert len(groups[category])>=64;rows.extend(groups[category][:64])
    assert len(rows)==512
    rng.shuffle(rows);p=out/'train.jsonl';p.write_text(''.join(json.dumps(x)+'\n' for x in rows))
    (out/'manifest.json').write_text(json.dumps({'repo':'databricks/databricks-dolly-15k','revision':REV,'license':'CC-BY-SA-3.0','source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'selected_counts':dict(collections.Counter(r['task'] for r in rows)),'prompt_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'note':'Only instructions/context used; all responses will be regenerated by frozen Qwen. Exact normalized evaluation dedup, not semantic decontamination.'},indent=2))
if __name__=='__main__':main()
